#!/bin/bash

# Script to download images from Figma designs
# This script provides instructions and a template for downloading images

echo "=========================================="
echo "Figma Image Download Instructions"
echo "=========================================="
echo ""
echo "To download images from Figma:"
echo ""
echo "1. Open the Figma design in your browser:"
echo ""
echo "   CHECKOUT SCREENS:"
echo "   - Main Checkout Screen: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12660-18446&t=E4yWaE9f8HAvguXp-4"
echo "   - Empty Cart: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12581-16824&t=E4yWaE9f8HAvguXp-4"
echo "   - Cart Without Address: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12581-20011&t=E4yWaE9f8HAvguXp-4"
echo "   - Cart With Address: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12626-15711&t=E4yWaE9f8HAvguXp-4"
echo "   - Delivery Tip Popup: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12626-16529&t=E4yWaE9f8HAvguXp-4"
echo "   - Coupon Success: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12635-18100&t=E4yWaE9f8HAvguXp-4"
echo "   - Explore Now: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12635-17734&t=E4yWaE9f8HAvguXp-4"
echo ""
echo "   ORDER STATUS SCREENS:"
echo "   - Main Screen: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12635-25875&t=E4yWaE9f8HAvguXp-4"
echo "   - Second Screen: https://www.figma.com/design/SkUi0997ZLBHlmE9s7KKU6/selorg--Final---12.09.24?node-id=12635-26998&t=E4yWaE9f8HAvguXp-4"
echo ""
echo "2. In Figma:"
echo "   - Select the frame/component you want to export"
echo "   - In the right sidebar, find the 'Export' section"
echo "   - Click the '+' button to add an export setting"
echo "   - Choose format: PNG or JPG"
echo "   - Choose scale: 2x or 3x for high resolution"
echo "   - Click 'Export [name]' button"
echo ""
echo "3. For individual images within the design:"
echo "   - Select the image element"
echo "   - Right-click and choose 'Copy as PNG' or use Export"
echo "   - Save to: Frontend/src/assets/images/"
echo ""
echo "4. Recommended image names:"
echo ""
echo "   CHECKOUT SCREEN IMAGES:"
echo "   - checkout-empty-cart.png (empty cart illustration)"
echo "   - checkout-product-1.png (product image for cart item 1)"
echo "   - checkout-product-2.png (product image for cart item 2)"
echo "   - explore-now-background.png (explore now card background image)"
echo ""
echo "   ORDER STATUS SCREEN IMAGES:"
echo "   - order-status-main-bg.png (main screen background/map)"
echo "   - order-status-main-product.png (product image in main screen)"
echo "   - order-status-main-delivery-partner.png (delivery partner avatar)"
echo "   - order-items-detail-product-1.png (product images in detail screen)"
echo "   - order-items-detail-product-2.png"
echo ""
echo "5. After downloading, place images in:"
echo "   Frontend/src/assets/images/"
echo ""
echo "=========================================="
echo "Alternative: Use Figma API"
echo "=========================================="
echo ""
echo "If you have Figma API access, you can use:"
echo "  - Figma API to export images programmatically"
echo "  - Figma plugins for batch export"
echo ""
echo "For now, please manually export the images and place them in:"
echo "  Frontend/src/assets/images/"
echo ""

